apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
    processors:
    exporters:
      logging:
        loglevel: debug
      otlp:
        endpoint: {{ .Values.grafana.endpoint }}:443
        headers:
          authorization: Basic {{ .Values.grafana.digest }}
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging,otlp]