apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
    replicas: 1
    selector:
        matchLabels:
          app: app1
    template:
        metadata:
          labels:
              app: app1
        spec:
          containers:
          - name: app1
            image: "{{ .Values.image.organization }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: Always
            ports:
            - containerPort: 8080
          - name: agent
            image: otel/opentelemetry-collector:0.18.0
            args:
            - --config=/conf/agent.yaml
            volumeMounts:
            - mountPath: /conf
              name: agent-config
          volumes:
          - configMap:
              items:
              - key: agent.yaml
                path: agent.yaml
              name: agent-config
            name: agent-config